const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let DATA=null,filter='All',countdownTimer=null,quoteTimer=null;
const tzFmt=(d,tz,opts={})=>new Intl.DateTimeFormat('en-US',{timeZone:tz,...opts}).format(d);
const TEAM_META={
'AFC Bournemouth':{id:'349',color:'da291c'},'Arsenal':{id:'359',color:'ef0107'},'Aston Villa':{id:'362',color:'670e36'},'Brentford':{id:'337',color:'e30613'},'Brighton & Hove Albion':{id:'331',color:'0057b8'},'Chelsea':{id:'363',color:'034694'},'Coventry City':{id:'388',color:'69b3e7'},'Crystal Palace':{id:'384',color:'1b458f'},'Everton':{id:'368',color:'003399'},'Fulham':{id:'370',color:'111111'},'Hull City':{id:'306',color:'f5a12d'},'Ipswich Town':{id:'373',color:'0044aa'},'Leeds United':{id:'357',color:'1d428a'},'Liverpool':{id:'364',color:'c8102e'},'Manchester City':{id:'382',color:'6cabdd'},'Manchester United':{id:'360',color:'da291c'},'Newcastle United':{id:'361',color:'241f20'},'Nottingham Forest':{id:'393',color:'dd0000'},'Sunderland':{id:'366',color:'eb172b'},'Tottenham Hotspur':{id:'367',color:'132257'}
};
const DISPLAY_TEAM={'Manchester United':'ManCunt'};const displayTeam=name=>DISPLAY_TEAM[name]||name;
function updateClocks(){const n=new Date();$('#clockET').textContent='ET '+tzFmt(n,'America/New_York',{hour:'numeric',minute:'2-digit'});$('#clockUK').textContent='Liverpool '+tzFmt(n,'Europe/London',{hour:'numeric',minute:'2-digit'});$('#clockCT').textContent='CT '+tzFmt(n,'America/Chicago',{hour:'numeric',minute:'2-digit'});}updateClocks();setInterval(updateClocks,30000);
async function weather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=53.4084&longitude=-2.9916&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph');const j=await r.json(),c=j.current;const icon=c.weather_code<2?'☀':c.weather_code<4?'⛅':c.weather_code<60?'☁':'☂';$('#weather').innerHTML=`<span class="weather-icon">${icon}</span><div><strong>Liverpool</strong><span>${Math.round(c.temperature_2m)}°F • feels ${Math.round(c.apparent_temperature)}° • ${Math.round(c.wind_speed_10m)} mph</span></div>`}catch(e){$('#weather').innerHTML='<span class="weather-icon">⌂</span><div><strong>Liverpool</strong><span>Merseyside • L4</span></div>'}}weather();
function fmtET(d){return tzFmt(d,'America/New_York',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}function fmtUK(d){return tzFmt(d,'Europe/London',{hour:'numeric',minute:'2-digit',timeZoneName:'short'})}function fmtCT(d){return tzFmt(d,'America/Chicago',{hour:'numeric',minute:'2-digit'})}
function nextFixture(){return DATA.fixtures.map(x=>({...x,dt:new Date(x.date)})).filter(x=>x.status!=='final'&&x.dt>Date.now()-7200000).sort((a,b)=>a.dt-b.dt)[0]}
function renderNext(){const g=nextFixture();if(!g){$('#nextMatch').innerHTML='<div class="panel"><div class="ucl-status">No upcoming fixture found.</div></div>';return}const opp=displayTeam(g.opponent),when=g.homeAway==='H'?`Liverpool v ${opp}`:`${opp} v Liverpool`;$('#nextMatch').classList.remove('skeleton');$('#nextMatch').innerHTML=`<article class="match-hero"><div class="match-top"><span class="comp-pill">${g.competition}</span><span class="venue">${g.venue||''}</span></div><div class="versus"><div class="where">${g.homeAway==='H'?'Anfield • Home':'Away'}</div><h3>${when}</h3><div class="times"><div><strong>${tzFmt(g.dt,'America/New_York',{weekday:'short',month:'short',day:'numeric'})}<br>${tzFmt(g.dt,'America/New_York',{hour:'numeric',minute:'2-digit'})} ET</strong><span>GROUP CHAT TIME</span></div><div><strong>${fmtUK(g.dt)}</strong><span>LIVERPOOL</span></div><div><strong>${fmtCT(g.dt)} CT</strong><span>MATT</span></div></div></div></article><aside class="watch-card"><div><span class="label">WHERE TO WATCH • USA</span><div class="network">${g.broadcastUS||'TBA'}</div><p class="broadcast-note">${g.broadcastUS&&g.broadcastUS!=='TBA'?'Confirmed U.S. outlet':'U.S. outlet not yet specifically confirmed'}</p></div><a href="#watch">Full U.S. broadcast guide ↓</a></aside>`;countdown(g.dt);}
function countdown(dt){if(countdownTimer)clearInterval(countdownTimer);const pad=n=>String(Math.max(0,n)).padStart(2,'0');const tick=()=>{const ms=dt-Date.now();const root=$('#countdown');if(!root)return;if(ms<=0){root.innerHTML='<div class="matchday-now">MATCHDAY</div>';clearInterval(countdownTimer);return}const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);$('#cdDays').textContent=pad(d);$('#cdHours').textContent=pad(h);$('#cdMinutes').textContent=pad(m);$('#cdSeconds').textContent=pad(s)};tick();countdownTimer=setInterval(tick,1000)}
function fixtureFits(g){if(filter==='All')return true;if(filter==='Cups')return !['Premier League','Champions League'].includes(g.competition);return g.competition===filter}
function fixtureMarkup(g){const past=g.status==='final',score=past?`<div class="score">${g.scoreFor}–${g.scoreAgainst}</div>`:`<span class="ha">${g.homeAway}</span>`;return `<div class="fixture ${past?'past':''}"><div class="datebox"><strong>${tzFmt(g.dt,'America/New_York',{month:'short',day:'numeric'})}</strong><span>${tzFmt(g.dt,'America/New_York',{weekday:'short'})}</span></div><div class="opponent">${score}<div><b>${displayTeam(g.opponent)}</b><small>${g.competition} • ${g.venue||''}</small></div></div><div class="fixture-time"><strong>${past?'FINAL':tzFmt(g.dt,'America/New_York',{hour:'numeric',minute:'2-digit'})+' ET'}</strong>${!past?`<span>${fmtUK(g.dt)} • ${fmtCT(g.dt)} CT</span>`:''}</div><div class="broadcast ${g.broadcastUS==='TBA'?'tba':''}">${past?'':(g.broadcastUS||'TBA')}</div></div>`}
function renderFixtures(){const list=DATA.fixtures.map(x=>({...x,dt:new Date(x.date)})).filter(fixtureFits).sort((a,b)=>a.dt-b.dt),root=$('#fixtureList');root.innerHTML='';if(!list.length){root.innerHTML='<div class="ucl-status">Fixtures will appear here once announced.</div>';return}const groups=new Map();list.forEach(g=>{const key=tzFmt(g.dt,'Europe/London',{year:'numeric',month:'2-digit'}),label=tzFmt(g.dt,'Europe/London',{month:'long',year:'numeric'});if(!groups.has(key))groups.set(key,{label,games:[]});groups.get(key).games.push(g)});const mobile=window.matchMedia('(max-width:800px)').matches,now=new Date(),currentKey=tzFmt(now,'Europe/London',{year:'numeric',month:'2-digit'}),keys=[...groups.keys()],openKey=groups.has(currentKey)?currentKey:keys.find(k=>groups.get(k).games.some(g=>g.dt>=now))||keys[0];groups.forEach((group,key)=>{const open=!mobile||key===openKey;root.insertAdjacentHTML('beforeend',`<details class="fixture-month" ${open?'open':''}><summary class="month"><span>${group.label}</span><span class="month-meta">${group.games.length} ${group.games.length===1?'match':'matches'} <i aria-hidden="true"></i></span></summary><div class="month-fixtures">${group.games.map(fixtureMarkup).join('')}</div></details>`)})}
function renderTable(id,rows){const tb=$(id+' tbody');tb.innerHTML='';const data=rows||[],leader=Math.max(0,...data.map(r=>Number(r.pts)||0));data.forEach((r,i)=>{const meta=TEAM_META[r.team]||{},teamId=r.teamId||meta.id||'',logo=r.logo||(teamId?`https://a.espncdn.com/i/teamlogos/soccer/500/${teamId}.png`:''),color=r.color||meta.color||'999999',trailing=leader-(Number(r.pts)||0),teamLabel=displayTeam(r.team),crest=logo?`<img class="club-crest" src="${logo}" alt="${teamLabel} crest" loading="lazy">`:'';const accent=` style="--club-color:#${String(color).replace('#','')}"`;tb.insertAdjacentHTML('beforeend',`<tr class="${r.team==='Liverpool'?'liverpool':''}"${accent}><td>${r.pos||i+1}</td><td><div class="club-cell"><span class="club-color"></span>${crest}<span>${teamLabel}</span></div></td><td>${r.p??0}</td><td>${r.w??0}</td><td>${r.d??0}</td><td>${r.l??0}</td><td>${r.gf??0}</td><td>${r.ga??0}</td><td>${(r.gd??0)>0?'+':''}${r.gd??0}</td><td><b>${r.pts??0}</b></td><td class="trailing">${trailing===0?'—':trailing}</td></tr>`)})}
function renderTables(){renderTable('#plTable',DATA.premierLeagueTable);renderTable('#uclTable',DATA.championsLeagueTable);$('#uclStatus').textContent=DATA.championsLeagueStatus||'';$('#uclTable').style.display=(DATA.championsLeagueTable||[]).length?'table':'none'}
function renderNews(){const n=$('#newsGrid');n.innerHTML='';(DATA.news||[]).slice(0,12).forEach(x=>{const d=x.published?new Date(x.published):null;n.insertAdjacentHTML('beforeend',`<a class="news-card" target="_blank" rel="noopener" href="${x.url}"><span class="source">${x.source}</span><h3>${x.title}</h3><time>${d?tzFmt(d,'America/New_York',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):''}</time></a>`)})}
const MAIN_ROOM_QUOTES=[{text:"There’s nothing more dangerous than a 2-0 lead.",by:'Matt Hurley'},{text:"I don't know where he is, but I hope that Sergio Ramos is having a terrible day. Fuck that guy",by:'Matt Dayton'},{text:'Bathroom',by:'Anonymous (All of us)'},{text:'Corner Taken Quickly....Origi!',by:'Steve Hunter'},{text:"I'm calling it. One more goal and this one's over",by:'Jack Sheahan'}];
function initQuotes(){const el=$('#rotatingQuote'),dots=$('#quoteDots');if(!el||!MAIN_ROOM_QUOTES.length)return;let i=0;dots.innerHTML=MAIN_ROOM_QUOTES.map((_,n)=>`<span class="${n===0?'active':''}"></span>`).join('');const show=()=>{const q=MAIN_ROOM_QUOTES[i];el.classList.remove('quote-show');void el.offsetWidth;el.innerHTML=`“${q.text}” <span>— ${q.by}</span>`;el.classList.add('quote-show');[...dots.children].forEach((d,n)=>d.classList.toggle('active',n===i));i=(i+1)%MAIN_ROOM_QUOTES.length};show();if(MAIN_ROOM_QUOTES.length>1){if(quoteTimer)clearInterval(quoteTimer);quoteTimer=setInterval(show,7000)}}initQuotes();
async function init(){try{const r=await fetch('site-data.json?'+Date.now());DATA=await r.json();const u=new Date(DATA.updated);$('#updated').textContent='Updated '+fmtET(u);$('#footerUpdated').textContent='Data '+fmtET(u);renderNext();renderFixtures();renderTables();renderNews()}catch(e){$('#nextMatch').innerHTML='<div class="panel"><div class="ucl-status">Data is refreshing. Try again shortly.</div></div>'}}init();$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderFixtures()});
let fixtureLayoutTimer;window.addEventListener('resize',()=>{clearTimeout(fixtureLayoutTimer);fixtureLayoutTimer=setTimeout(()=>{if(DATA)renderFixtures()},180)});