const $=s=>document.querySelector(s);
const DISPLAY_TEAM={'Manchester United':'ManCunt'};
const displayTeam=n=>DISPLAY_TEAM[n]||n;
const TEAM_META={'AFC Bournemouth':'349','Arsenal':'359','Aston Villa':'362','Brentford':'337','Brighton & Hove Albion':'331','Chelsea':'363','Coventry City':'388','Crystal Palace':'384','Everton':'368','Fulham':'370','Hull City':'306','Ipswich Town':'373','Leeds United':'357','Liverpool':'364','Manchester City':'382','Manchester United':'360','Newcastle United':'361','Nottingham Forest':'393','Sunderland':'366','Tottenham Hotspur':'367'};
const fmt=(d,o={})=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',...o}).format(d);
function renderTable(rows){const tb=$('#competitionTable tbody');tb.innerHTML='';const data=rows||[],leader=Math.max(0,...data.map(r=>Number(r.pts)||0));data.forEach((r,i)=>{const id=r.teamId||TEAM_META[r.team]||'',logo=r.logo||(id?`https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`:''),trail=leader-(Number(r.pts)||0);tb.insertAdjacentHTML('beforeend',`<tr class="${r.team==='Liverpool'?'liverpool':''}"><td>${r.pos||i+1}</td><td><div class="club-cell">${logo?`<img class="club-crest" src="${logo}" alt="" loading="lazy">`:''}<span>${displayTeam(r.team)}</span></div></td><td>${r.p??0}</td><td>${r.w??0}</td><td>${r.d??0}</td><td>${r.l??0}</td><td>${r.gf??0}</td><td>${r.ga??0}</td><td>${(r.gd??0)>0?'+':''}${r.gd??0}</td><td><b>${r.pts??0}</b></td><td>${trail===0?'—':trail}</td></tr>`)})}
function gameMarkup(g){const d=new Date(g.date),final=g.status==='final'&&g.homeScore!=null&&g.awayScore!=null;return `<div class="league-game"><div class="league-date"><strong>${fmt(d,{weekday:'short',month:'short',day:'numeric'})}</strong><span>${fmt(d,{hour:'numeric',minute:'2-digit'})} ET</span></div><div class="league-pair"><span class="home">${displayTeam(g.home)}</span><span class="league-score">${final?`${g.homeScore}–${g.awayScore}`:'v'}</span><span class="away">${displayTeam(g.away)}</span></div><div class="league-venue">${g.venue||''}</div></div>`}
function renderPL(matches){const root=$('#weeks');if(!matches?.length){root.innerHTML='<div class="competition-status">League schedule is refreshing. Please check back shortly.</div>';return}const byRound=new Map();matches.forEach(g=>{const r=Number(g.round)||0;if(!byRound.has(r))byRound.set(r,[]);byRound.get(r).push(g)});const now=Date.now(),rounds=[...byRound.keys()].sort((a,b)=>a-b);let current=rounds.find(r=>byRound.get(r).some(g=>new Date(g.date).getTime()>=now));if(!current)current=rounds[rounds.length-1];root.innerHTML='';rounds.forEach(r=>{const games=byRound.get(r).sort((a,b)=>new Date(a.date)-new Date(b.date)),first=new Date(games[0].date),last=new Date(games[games.length-1].date),isCurrent=r===current,label=`Matchweek ${r}`,dates=`${fmt(first,{month:'short',day:'numeric'})}–${fmt(last,{month:'short',day:'numeric'})}`;root.insertAdjacentHTML('beforeend',`<details class="week-block ${isCurrent?'current-week':''}" ${isCurrent?'open':''}><summary><span class="week-title">${label}${isCurrent?'<span class="round-badge">THIS WEEK</span>':''}</span><span class="week-meta">${dates} • ${games.length} matches</span></summary><div class="week-games">${games.map(gameMarkup).join('')}</div></details>`)})}
function renderUCL(comp){const root=$('#weeks');if(comp.championsLeagueMatches?.length){const byRound=new Map();comp.championsLeagueMatches.forEach(g=>{const r=Number(g.round)||0;if(!byRound.has(r))byRound.set(r,[]);byRound.get(r).push(g)});const now=Date.now(),rounds=[...byRound.keys()].sort((a,b)=>a-b),current=rounds.find(r=>byRound.get(r).some(g=>new Date(g.date).getTime()>=now))||rounds[rounds.length-1];root.innerHTML='';rounds.forEach(r=>{const games=byRound.get(r).sort((a,b)=>new Date(a.date)-new Date(b.date)),isCurrent=r===current;root.insertAdjacentHTML('beforeend',`<details class="week-block ${isCurrent?'current-week':''}" ${isCurrent?'open':''}><summary><span class="week-title">Matchday ${r}${isCurrent?'<span class="round-badge">CURRENT</span>':''}</span><span class="week-meta">${games.length} matches</span></summary><div class="week-games">${games.map(gameMarkup).join('')}</div></details>`)})}else{root.innerHTML=`<div class="competition-status">${comp.championsLeagueStatus||'Champions League league-phase fixtures have not yet been published.'}</div>${(comp.championsLeagueMatchdays||[]).map(m=>`<details class="week-block"><summary><span class="week-title">${m.label}</span><span class="week-meta">${m.dates}</span></summary><div class="week-games"><div class="competition-status">Fixtures will appear here automatically after the league-phase draw.</div></div></details>`).join('')}`}}
async function init(){const kind=document.body.dataset.competition;try{const [siteR,compR]=await Promise.all([fetch('site-data.json?'+Date.now()),fetch('competition-data.json?'+Date.now())]);const site=await siteR.json(),comp=await compR.json();$('#dataStamp').textContent='Updated '+fmt(new Date(comp.updated||site.updated),{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});if(kind==='pl'){renderPL(comp.premierLeagueMatches);renderTable(site.premierLeagueTable)}else{renderUCL(comp);renderTable(site.championsLeagueTable);if(!(site.championsLeagueTable||[]).length)$('#tableStatus').textContent=site.championsLeagueStatus||'League-phase table will appear after Matchday 1.'}}catch(e){$('#weeks').innerHTML='<div class="competition-status">Competition data is refreshing. Try again shortly.</div>'}}
init();