const $=s=>document.querySelector(s);
const DISPLAY_TEAM={'Manchester United':'ManCunt'};
const displayTeam=n=>DISPLAY_TEAM[n]||n;
const fmt=(d,o={})=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',...o}).format(d);
const fmtUK=(d,o={})=>new Intl.DateTimeFormat('en-US',{timeZone:'Europe/London',...o}).format(d);
const RAW='https://raw.githubusercontent.com/mmhpdayton/MainRoomLiverpool/main/site-data.json';
let LAST=null;
function dataCompetition(){return document.body.dataset.competition==='fa'?'FA Cup':'Carabao Cup'}
function displayCompetition(){return document.body.dataset.competition==='fa'?'FA Cup':'Milk Cup'}
function gameMarkup(g){const d=new Date(g.date),final=g.status==='final',live=g.status==='live',hasScore=(final||live)&&g.scoreFor!=null&&g.scoreAgainst!=null;const home=g.homeAway==='H'?'Liverpool':g.opponent,away=g.homeAway==='H'?g.opponent:'Liverpool';const hs=g.homeAway==='H'?g.scoreFor:g.scoreAgainst,as=g.homeAway==='H'?g.scoreAgainst:g.scoreFor;const score=hasScore?`${hs}–${as}`:'v';const status=live?`<span class="live-badge">LIVE${g.liveStatus?' • '+g.liveStatus:''}</span>`:(final?'<span class="final-badge">FINAL</span>':'');const broadcast=!final?`<div class="league-venue"><b>US:</b> ${g.broadcastUS||'TBA'}${g.broadcastUSSpanish&&g.broadcastUSSpanish!=='TBA'?` • <b>ES:</b> ${g.broadcastUSSpanish}`:''}</div>`:'';return `<div class="league-game ${live?'is-live':''}"><div class="league-date"><strong>${fmt(d,{weekday:'short',month:'short',day:'numeric'})}</strong><span>${live?'IN PROGRESS':fmt(d,{hour:'numeric',minute:'2-digit'})+' ET'}</span></div><div class="league-pair"><span class="home">${displayTeam(home)}</span><span class="league-score">${score}${status}</span><span class="away">${displayTeam(away)}</span></div><div class="league-venue">${g.venue||''} • ${fmtUK(d,{hour:'numeric',minute:'2-digit',timeZoneName:'short'})}</div>${broadcast}</div>`}
function paint(data){LAST=data;const comp=dataCompetition(),games=(data.fixtures||[]).filter(g=>g.competition===comp).sort((a,b)=>new Date(a.date)-new Date(b.date));$('#dataStamp').textContent='Updated '+fmt(new Date(data.updated),{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});const root=$('#weeks');if(!games.length){root.innerHTML=`<div class="competition-status">Liverpool's ${displayCompetition()} fixtures will appear here as soon as the tie is confirmed.</div>`;return}const now=Date.now();root.innerHTML=games.map((g,i)=>`<details class="week-block ${new Date(g.date).getTime()>=now&&games.slice(0,i).every(x=>new Date(x.date).getTime()<now)?'current-week':''}" ${new Date(g.date).getTime()>=now&&games.slice(0,i).every(x=>new Date(x.date).getTime()<now)?'open':''}><summary><span class="week-title">${displayCompetition()}${g.round?` • Round ${g.round}`:''}</span><span class="week-meta">${fmt(new Date(g.date),{month:'short',day:'numeric'})} • ${displayTeam(g.opponent)}</span></summary><div class="week-games">${gameMarkup(g)}</div></details>`).join('')}
async function loadFresh(){try{const r=await fetch(RAW+'?'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('data');paint(await r.json())}catch(e){if(!LAST)$('#weeks').innerHTML='<div class="competition-status">Cup data is refreshing. Try again shortly.</div>'}}
loadFresh();setInterval(loadFresh,60000);
