const $=s=>document.querySelector(s);
const DISPLAY_TEAM={'Manchester United':'ManCunt'};
const displayTeam=n=>DISPLAY_TEAM[n]||n;
const fmt=(d,o={})=>new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',...o}).format(d);
const fmtUK=(d,o={})=>new Intl.DateTimeFormat('en-US',{timeZone:'Europe/London',...o}).format(d);
const RAW='https://raw.githubusercontent.com/mmhpdayton/MainRoomLiverpool/main/competition-data.json';
let LAST=null;
function displayCompetition(){return document.body.dataset.competition==='fa'?'FA Cup':'Milk Cup'}
function dataKey(){return document.body.dataset.competition==='fa'?'faCupMatches':'milkCupMatches'}
function gameMarkup(g){const d=new Date(g.date),final=g.status==='final',live=g.status==='live',hasScore=(final||live)&&g.homeScore!=null&&g.awayScore!=null,score=hasScore?`${g.homeScore}–${g.awayScore}`:'v',status=live?`<span class="live-badge">LIVE${g.liveStatus?' • '+g.liveStatus:''}</span>`:(final?'<span class="final-badge">FINAL</span>':'');return `<div class="league-game ${live?'is-live':''} ${g.home==='Liverpool'||g.away==='Liverpool'?'liverpool-cup-game':''}"><div class="league-date"><strong>${fmt(d,{weekday:'short',month:'short',day:'numeric'})}</strong><span>${live?'IN PROGRESS':fmt(d,{hour:'numeric',minute:'2-digit'})+' ET'}</span></div><div class="league-pair"><span class="home">${displayTeam(g.home)}</span><span class="league-score">${score}${status}</span><span class="away">${displayTeam(g.away)}</span></div><div class="league-venue">${g.venue||''}${g.venue?' • ':''}${fmtUK(d,{hour:'numeric',minute:'2-digit',timeZoneName:'short'})}</div></div>`}
function roundLabel(g){if(g.roundName)return g.roundName;if(g.round)return `Round ${g.round}`;return displayCompetition()}
function paint(data){LAST=data;const games=(data[dataKey()]||[]).slice().sort((a,b)=>new Date(a.date)-new Date(b.date));$('#dataStamp').textContent='Updated '+fmt(new Date(data.updated),{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});const root=$('#weeks');if(!games.length){root.innerHTML=`<div class="competition-status">${displayCompetition()} competition data is refreshing.</div>`;return}const groups=new Map();games.forEach(g=>{const key=roundLabel(g);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(g)});const now=Date.now(),entries=[...groups.entries()];let current=entries.findIndex(([,gs])=>gs.some(g=>g.status==='live'));if(current<0)current=entries.findIndex(([,gs])=>gs.some(g=>new Date(g.date).getTime()>=now));if(current<0)current=entries.length-1;root.innerHTML='';entries.forEach(([label,gs],i)=>{gs.sort((a,b)=>new Date(a.date)-new Date(b.date));const first=new Date(gs[0].date),last=new Date(gs[gs.length-1].date),dateText=fmt(first,{month:'short',day:'numeric'})+(gs.length>1&&first.toDateString()!==last.toDateString()?`–${fmt(last,{month:'short',day:'numeric'})}`:'');root.insertAdjacentHTML('beforeend',`<details class="week-block ${i===current?'current-week':''}" ${i===current?'open':''}><summary><span class="week-title">${displayCompetition()} • ${label}</span><span class="week-meta">${dateText} • ${gs.length} ${gs.length===1?'match':'matches'}</span></summary><div class="week-games">${gs.map(gameMarkup).join('')}</div></details>`)})}
async function loadFresh(){try{const r=await fetch(RAW+'?'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('data');paint(await r.json())}catch(e){if(!LAST)$('#weeks').innerHTML='<div class="competition-status">Cup data is refreshing. Try again shortly.</div>'}}
loadFresh();setInterval(loadFresh,60000);
