(()=>{
const aliasText=s=>s.replaceAll('Carabao Cup','Milk Cup');
const compLabel=s=>s==='Carabao Cup'?'Milk Cup':s;
const fmt=(d,tz,o={})=>new Intl.DateTimeFormat('en-US',{timeZone:tz,...o}).format(d);
const teamMeta={Liverpool:{id:'364'},'Tottenham Hotspur':{id:'367'}};
function ensureRedesign(){if(document.querySelector('link[data-main-room-redesign]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='redesign.css?v=20260914-2';link.dataset.mainRoomRedesign='1';document.head.appendChild(link)}
function alias(root=document.body){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.nodeValue&&n.nodeValue.includes('Carabao Cup'))n.nodeValue=aliasText(n.nodeValue)})}
function ensureTabs(){document.querySelectorAll('.competition-tabs').forEach(nav=>{if(!nav.querySelector('a[href="fa-cup.html"]'))nav.insertAdjacentHTML('beforeend','<a href="fa-cup.html">FA Cup</a>');if(!nav.querySelector('a[href="milk-cup.html"]'))nav.insertAdjacentHTML('beforeend','<a href="milk-cup.html">Milk Cup</a>')})}
function ensureFixtureFilters(){const filters=document.querySelector('#fixtures .filters');if(!filters)return;const cups=filters.querySelector('[data-filter="Cups"]');if(cups)cups.remove();if(!filters.querySelector('[data-filter="FA Cup"]'))filters.insertAdjacentHTML('beforeend','<button data-filter="FA Cup">FA Cup</button>');if(!filters.querySelector('[data-filter="Carabao Cup"]'))filters.insertAdjacentHTML('beforeend','<button data-filter="Carabao Cup">Milk Cup</button>')}
function bindFilters(){if(typeof renderFixtures!=='function')return;document.querySelectorAll('#fixtures [data-filter]').forEach(b=>{if(b.dataset.chromeBound)return;b.dataset.chromeBound='1';b.onclick=()=>{document.querySelectorAll('#fixtures [data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderFixtures()}})}
function logo(name){let id=teamMeta[name]?.id;try{if(!id&&typeof TEAM_META!=='undefined')id=TEAM_META[name]?.id}catch(e){}return id?`https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`:''}
function modernNext(){if(typeof nextFixture!=='function'||typeof DATA==='undefined'||!DATA?.fixtures)return;const root=document.querySelector('#nextMatch');if(!root)return;const g=nextFixture();if(!g)return;const stamp=`${g.id||''}|${g.date}|${g.status}|${g.scoreFor}|${g.scoreAgainst}|${g.broadcastUS}`;if(root.dataset.modernStamp===stamp)return;const d=new Date(g.date),home=g.homeAway==='H'?'Liverpool':g.opponent,away=g.homeAway==='H'?g.opponent:'Liverpool',homeLogo=logo(home),awayLogo=logo(away),competition=compLabel(g.competition),broadcast=(g.competition==='Carabao Cup'&&g.opponent==='Tottenham Hotspur')?'Paramount+':(g.broadcastUS||'TBA'),live=g.status==='live',score=live&&g.scoreFor!=null&&g.scoreAgainst!=null?`<div class="modern-live-score"><span>LIVE${g.liveStatus?' • '+g.liveStatus:''}</span><strong>${g.homeAway==='H'?g.scoreFor:g.scoreAgainst}–${g.homeAway==='H'?g.scoreAgainst:g.scoreFor}</strong></div>`:'<div class="modern-vs">VS</div>',round=g.round?` • Round ${g.round}`:'';
root.classList.remove('skeleton');root.dataset.modernStamp=stamp;root.innerHTML=`<article class="modern-match-card"><div class="modern-card-top"><span class="modern-comp-pill">🏆 ${competition}</span><span class="modern-venue">${g.venue||''}</span></div><div class="modern-teams"><div class="modern-team">${homeLogo?`<img src="${homeLogo}" alt="${home} crest">`:''}<strong>${typeof displayTeam==='function'?displayTeam(home):home}</strong></div>${score}<div class="modern-team">${awayLogo?`<img src="${awayLogo}" alt="${away} crest">`:''}<strong>${typeof displayTeam==='function'?displayTeam(away):away}</strong></div></div><div class="modern-meta"><div class="modern-meta-block"><span class="modern-meta-label">Match Time</span><span class="modern-meta-value">${live?'LIVE NOW':fmt(d,'America/New_York',{weekday:'short',month:'short',day:'numeric'})+'<br>'+fmt(d,'America/New_York',{hour:'numeric',minute:'2-digit'})+' ET'}</span><span class="modern-meta-sub">${fmt(d,'Europe/London',{hour:'numeric',minute:'2-digit',timeZoneName:'short'})}</span></div><div class="modern-meta-block"><span class="modern-meta-label">Watch Live (US)</span><span class="modern-meta-value">${broadcast}</span><span class="modern-meta-sub">${broadcast==='TBA'?'Awaiting confirmed listing':'Confirmed U.S. outlet'}</span></div><div class="modern-meta-block"><span class="modern-meta-label">Venue</span><span class="modern-meta-value">${g.venue||'TBA'}</span><span class="modern-meta-sub">${g.homeAway==='H'?'Liverpool, ENG':'Away'}</span></div></div><div class="modern-card-footer"><span>ⓘ <strong>${competition}</strong>${round} • 2026–27</span><span>${fmt(d,'America/Chicago',{hour:'numeric',minute:'2-digit'})} CT • Matt</span></div></article><a class="match-preview-button" href="#fixtures">Match Preview <span>→</span></a>`}
function enforceSpursMilkCupStream(){document.querySelectorAll('#fixtureList .fixture').forEach(row=>{if(row.textContent.includes('Tottenham Hotspur')&&(row.textContent.includes('Milk Cup')||row.textContent.includes('Carabao Cup'))){const bc=row.querySelector('.broadcast');if(bc&&(bc.textContent.trim()==='TBA'||!bc.textContent.trim())){bc.classList.remove('tba');bc.innerHTML='<span>Paramount+</span>'}}})}
let queued=false;function paint(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;ensureRedesign();ensureTabs();ensureFixtureFilters();bindFilters();modernNext();alias();enforceSpursMilkCupStream()})}
paint();const mo=new MutationObserver(paint);mo.observe(document.documentElement,{subtree:true,childList:true,characterData:true});
})();